/*
SQLyog Ultimate v11.11 (64 bit)
MySQL - 5.5.5-10.1.38-MariaDB : Database - new_vasco
*********************************************************************
*/

/*!40101 SET NAMES utf8 */;

/*!40101 SET SQL_MODE=''*/;

/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;
CREATE DATABASE /*!32312 IF NOT EXISTS*/`new_vasco` /*!40100 DEFAULT CHARACTER SET latin1 */;

USE `new_vasco`;

/*Table structure for table `tipo_movimientosjf` */

DROP TABLE IF EXISTS `tipo_movimientosjf`;

CREATE TABLE `tipo_movimientosjf` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `codigo` varchar(10) DEFAULT NULL,
  `descripcion` varchar(150) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=28 DEFAULT CHARSET=latin1;

/*Data for the table `tipo_movimientosjf` */

insert  into `tipo_movimientosjf`(`id`,`codigo`,`descripcion`) values (1,'E01','INVENTARIO INICIAL'),(2,'E02','INGRESO DE MATERIA PRIMA'),(3,'E03','SOBRANTES'),(4,'E04','AJUSTES DE INV.'),(5,'E05','NOTA DE CREDITO'),(6,'E12','INGRESO POR CAMBIO-COLOR'),(7,'E20','PRODUCCION'),(8,'E21','INGRESOS POR DEVOLUCIONES PROF'),(9,'E22','INGRESOS POR  INDUSTRIAS VASQUE'),(10,'E50','RETORNO DE PRENDAS'),(11,'S01','GUIA DE REMISION'),(12,'S02','BOLETA DE VENTAS'),(13,'S03','FACTURAS'),(14,'S04','SALIDA DE MATERIA PRIMA'),(15,'S05','FALTANTES'),(16,'S12','SALIDA POR CAMBIO-COLO'),(17,'S15','SALIDAS POR MUESTRAS VARIAS'),(18,'S16','SALIDA POR SEGUNDAS'),(19,'S17','SALIDA POR DESCUENTOS'),(20,'S18','SALIDA DE PRENDAS INCOMPLETAS'),(21,'S19','SALIDAS APT INDUSTRIAS VASQUEZ'),(22,'S20','SALIDAS POR OBSEQUIOS'),(23,'S21','SALIDA AJUST INV'),(24,'S55','VENTAS SWEET KISS'),(25,'S60','PEDIDOS'),(26,'S70','PROFORMAS'),(27,'S96','PEDIDOS SIN AUT');

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;
