/*
SQLyog Ultimate v11.11 (64 bit)
MySQL - 5.5.5-10.1.38-MariaDB : Database - new_vasco
*********************************************************************
*/

/*!40101 SET NAMES utf8 */;

/*!40101 SET SQL_MODE=''*/;

/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;
CREATE DATABASE /*!32312 IF NOT EXISTS*/`new_vasco` /*!40100 DEFAULT CHARACTER SET latin1 */;

USE `new_vasco`;

/*Table structure for table `tipo_pagosjf` */

DROP TABLE IF EXISTS `tipo_pagosjf`;

CREATE TABLE `tipo_pagosjf` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `codigo` varchar(10) DEFAULT NULL,
  `descripcion` varchar(150) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=32 DEFAULT CHARSET=latin1;

/*Data for the table `tipo_pagosjf` */

insert  into `tipo_pagosjf`(`id`,`codigo`,`descripcion`) values (1,'00','LETRAS BCP'),(2,'01','FACTURA'),(3,'02','RECIBOS POR HONORARIOS'),(4,'03','BOLETAS DE VENTAS'),(5,'04','CONTROL INTERNO-SALIDA ALMACEN'),(6,'05','DEP. CTACTE'),(7,'06','POS-BCP'),(8,'07','NOTA DE CREDITO'),(9,'08','NOTA DE DEBITO'),(10,'09','PROFORMAS'),(11,'10','DESCUENTO ADICIONAL PROFORMAS'),(12,'11','PROMOCION VENTA DE BRASIERES'),(13,'12','TICKET O CINTA EMITIDO POR MA'),(14,'13','DEVOL. PROFORMAS'),(15,'14','DEP. CULQI'),(16,'70','ENTREGA DE EFECTIVO'),(17,'71','PAGOS Y GASTOS'),(18,'72','CAJA CHICA DIA ANTERIOR'),(19,'80','EFECTIVO'),(20,'81','TARJETA DE CREDITO'),(21,'82','ABONO EN CTA. S/.'),(22,'83','ABONO EN CTA. US$'),(23,'84','CHEQUE'),(24,'85','LETRAS'),(25,'95','MUESTRAS DE VITRINAS / PANELES'),(26,'96','NOTA DE CREDITO DEVOLUCION'),(27,'97','NOTA DE CREDITO PRONTO PAGO '),(28,'98','AJUSTE DE CUENTAS NO EFECTIVO'),(29,'99','PERDIDA POR ROBO'),(30,'RF','REFINANCIACION'),(31,'TR','TELECREDITO');

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;
